apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hcwl
  name: hcwl-module-education
  labels:
    app: hcwl-module-education
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hcwl-module-education
  template:
    metadata:
      labels:
        app: hcwl-module-education
    spec:
      imagePullSecrets:
        - name: aliyun-registry-secret
      restartPolicy: Always
      containers:
        - name: hcwl-module-education
          imagePullPolicy: Always
          image: swr.cn-north-4.myhuaweicloud.com/zk-project/hcwl-module-education:latest
          ports:
            - containerPort: 9204
              name: http9204
              protocol: TCP
              hostPort: 9204
          volumeMounts:
            - mountPath: /hcwl
              name: nfs-volume
              readOnly: false
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-pvc